name: ai_mud
description: "a mud game built with flutter and LLM"
publish_to: 'none' 

version: 0.2.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  blur: ^4.0.0
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_radar_chart: ^0.2.1
  flutter_riverpod: ^2.5.1
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  langchain_lib:
    git:
      url: https://github.com/guchengxi1994/langchain_lib
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1
  showcaseview: ^3.0.0
  toastification: ^2.1.0
  window_manager: ^0.4.0
  

dev_dependencies:
  build_runner: any  # dart run build_runner build
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0
  package_rename: ^1.6.0   # dart run package_rename

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/settings/settings.json

flutter_launcher_icons:   # flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.jpeg"
