name: ai_mud
description: "a mud game built with flutter and LLM"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  blur: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  langchain_lib:
    git:
      url: https://github.com/guchengxi1994/langchain_lib
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1
  window_manager: ^0.3.9
  

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  json_serializable: ^6.8.0
  package_rename: ^1.6.0   # dart run package_rename
  

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
